### ISSUE TITLE
CI for Pull Requests

### ISSUE THREAD

**Issue by lelouvincx** [lelouvincx/Chinh-Dinh-training#10]
### Description
As a developer,
I want the codebase is well configured continuous integration.
So that my effort on setup duplicated tasks decreased.

### Requirements
Continuous Integration on Pull Requests (merged from branch to dev):
- [ ] Auto create pull request into development when a new branch is pushed #19 
- [x] Branch naming checking (feat, bug, ...) #20 
- [ ] Check whether this branch is conflicted in code. If yes, mark label 'conflict' and send message #21 
- [ ] Auto merge into development branch when pull request is accepted (There's an action name automerge) #22 
- [ ] Upstream App #23 
- [ ] Kafka-connect #24 
- [ ] Linting & formatting
- [x] Unit test (merged from branch to dev)
- [ ] Coverage (merged from branch to dev, upload artifact)
- [ ] Generating dependencies (on push)
- [ ] Documentation (on push, changed files in docs/**)
    - [ ] Database catalog
    - [ ] Diagram

### ACs
- Full CI descripted above

**Comment by lelouvincx** [comment]
Please clean out old branches and commits. We are about to apply new project management process.
